version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: 'mysql_password'
      MYSQL_ROOT_PASSWORD: 'mysql_root_password'
    ports:
      - '3306:3306'

  api:
    build:
      context: .
    depends_on:
      - db
    env_file: .env.prod
    restart: always
    ports:
      - '8080:8080'
